version: '3.6'

services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
